### ISSUE TITLE
error when creating an android application: Exception in thread "main" kotlin.UninitializedPropertyAccessException: lateinit property deepLink has not been initialized

### ISSUE THREAD

**Issue by anass-talii** [4d/4D-Mobile-App#51]
Build 
20.100653
20R3.287741
20R2.100220

SDK version
20.x@1.c6423802.7613ac6a.def37f97.a3d01c02

build of a simple application with text fields displays the following error:

Failed to create the project
Failed to generate files
```
Exception in thread "main" kotlin.UninitializedPropertyAccessException: lateinit property deepLink has not been initialized
	at kscript.scriplet.ProjectEditor.getDeepLink(Main.kt:2360)
	at kscript.scriplet.MustacheHelper.<init>(Main.kt:754)
	at kscript.scriplet.GenerateCommand.start(Main.kt:8647)
	at kscript.scriplet.GenerateCommand.run(Main.kt:8602)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:204)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:213)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:17)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:396)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:393)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:411)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:436)
	at kscript.scriplet.MainKt.main(Main.kt:8768)
```

Note: deep linking is not enabled in the project editor; and the following error is displayed when clicking on the publishing section:
 ```
   Error when executing the method "panel_Load" at line number 33

Object or Collection Expected.

Error code: -10716 (4DRT)
Object or Collection Expected.
component: '4DRT'
task -9, name: 'Design process'

Call chain:
[
	{
		"type": "projectMethod",
		"name": "panel_Load",
		"line": 33,
		"database": "4D Mobile App"
	},
	{
		"type": "projectMethod",
		"name": "panel_HANDLE_EVENT",
		"line": 1,
		"database": "4D Mobile App"
	}
]
```

**Comment by e-marchand** [comment]
1ère erreur ici https://github.com/4d/android-ProjectGenerator/issues/4
la version a retenir c'est pas celle donnée mais celle du project generator obtenu en lancant le jar avec l'option de version
donc j'invalide cette partie

sinon pour l'autre erreur, je fais de cette stack le bug

**Comment by e-marchand** [comment]
l'erreur correspond à la ligne 
https://github.com/4d/4D-Mobile-App/blob/main/Project/Sources/Methods/panel_Load.4dm#L34

**Comment by e-marchand** [comment]
peut être un soucis de feature pas activé suivant la version du composant ou de 4D

**Comment by e-marchand** [comment]
oui soucis de feature flag

c'est plutot Form.$dialog[$form]:=cs[$form].new() qui par en cacahète
c'est cs[$form] qui est undefined

avec $form = _FEATURES

or cette classe existe pas c'est FEATURES

dans le code le changement en fonction de la feature
```
	If (Feature.with("customLoginForms"))
		
		$o.panels.push(New object(\
		"title"; Get localized string("features"); \
		"form"; "FEATURES"))
		
	Else 
		
		$o.panels.push(New object(\
		"title"; Get localized string("features"); \
		"form"; "_FEATURES"))
		
	End if 
```

ca a du etre fixer si on a la feature activé, chose faite
